language: node_js
node_js:
  - stable

branches:
  only:
    - master
  except:
    - gh-pages

jobs:
  include:
    - name: install
      install:
        - npm install -g @angular/cli
    - name: lint
      script: ng lint
    - name: deploy
      script: ng build --prod --base-href=/meal-planner/
      deploy:
      - provider: pages
        skip-cleanup: true
        github-token: $GITHUB_TOKEN
        keep-history: true
        on:
          branch: master
        local_dir: dist/meal-planner/
        after_deploy: echo "Deployed to GH Pages"
